import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nunito = localFont({
  /* Paths relative to this file; colocate under app/ so Next bundles the files */
  src: [
    {
      path: "./_fonts/Nunito-VariableFont_wght.ttf",
      style: "normal",
      weight: "200 1000",
    },
    {
      path: "./_fonts/Nunito-Italic-VariableFont_wght.ttf",
      style: "italic",
      weight: "200 1000",
    },
  ],
  variable: "--font-nunito",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${nunito.variable} dark h-full font-sans antialiased`}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
